export const incorrectSentences = [
    { id: 6, source: "social media", text: "I seen a really good movie yesterday." },
    { id: 7, source: "forum post", text: "Their going to be a party at my place." },
    { id: 8, source: "comment section", text: "Who's car is that parked outside?" },
    { id: 9, source: "tweet", text: "Your not going to believe what happened!" },
    { id: 10, source: "blog comment", text: "The information was very helpfull." },
    { id: 11, source: "online review", text: "The food was okay, but the service were slow." },
    { id: 12, source: "social media", text: "Me and my friend went to the concert." },
    { id: 13, source: "forum post", text: "If I was you, I would complain." },
    { id: 14, source: "comment section", text: "There's less people here today than usual." },
    { id: 15, source: "tweet", text: "He don't know how to fix it." },
    { id: 16, source: "blog comment", text: "The company have announced new policies." },
    { id: 17, source: "online review", text: "It's a really unique of a product." },
    { id: 18, source: "social media", text: "She speaks English very good." },
    { id: 19, source: "forum post", text: "I'm not sure who's phone this is." },
    { id: 20, source: "comment section", text: "They was all laughing at the joke." },
    { id: 21, source: "tweet", text: "We should of gone to the beach." },
    { id: 22, source: "blog comment", text: "The reason why he was late is because..." },
    { id: 23, source: "online review", text: "The chairs wasn't very comfortable." },
    { id: 24, source: "social media", text: "Its important to stay hydrated." },
    { id: 25, source: "forum post", text: "Each of the students have their own opinion." },
    { id: 26, source: "comment section", text: "I could care less about the outcome." },
    { id: 27, source: "tweet", text: "Who did you give the book to?" },
    { id: 28, source: "blog comment", text: "The criteria for success is clearly defined." },
    { id: 29, source: "online review", text: "The staff was friendly and efficient." },
    { id: 30, source: "social media", text: "He is more taller than his brother." },
    { id: 31, source: "forum post", text: "Neither of them were interested." },
    { id: 32, source: "comment section", text: "It's a phenomena that is hard to explain." },
    { id: 33, source: "tweet", text: "I'm going too the store later." },
    { id: 34, source: "blog comment", text: "The affect of the new policy is significant." },
    { id: 35, source: "online review", text: "The quality of the materials were poor." },
    { id: 36, source: "social media", text: "My friend and I are going to the park." },
    { id: 37, source: "forum post", text: "Everyone have their own way of doing things." },
    { id: 38, source: "comment section", text: "There are less opportunities now." },
    { id: 39, source: "tweet", text: "She has went to the library." },
    { id: 40, source: "blog comment", text: "The principle reason for the delay was..." },
    { id: 41, source: "online review", text: "The service were excellent." },
    { id: 42, source: "social media", text: "He don't like pizza." },
    { id: 43, source: "forum post", text: "If he was here, he would know what to do." },
    { id: 44, source: "comment section", text: "Its a very interesting book." },
    { id: 45, source: "tweet", text: "They're coming over for dinner." },
    { id: 46, source: "blog comment", text: "The data shows a clear increase." },
    { id: 47, source: "online review", text: "The product wasn't as good as they said." },
    { id: 48, source: "social media", text: "Us students are organizing a protest." },
    { id: 49, source: "forum post", text: "Each participant have to register." },
    { id: 50, source: "comment section", text: "There's many things to consider." },
];